# Options
options:
   preprocessing: False
   registration_2d: False
   stacking: False
   registration_3d: False
   splitting_data: False
   regression: True
   evaluation: True

# Executables
exe:
   stacking: '/home/alina/Projects/ImageStacking4dMRI/build/ims4dMRI'
   registration_2d: '/home/alina/Projects/GraphDemons_3D/build_2d/gdr'
   registration_3d: '/home/alina/Projects/GraphDemons_3D/build_3d/gdr'
   regression_learn: '/home/alina/Projects/GPR/build/apps/gpLearn'
   regression_predict: '/home/alina/Projects/GPR/build/apps/gpPredict'

# General configuration
general:
   surrogate_type: -1 #  0 - MR navigators, 1 - ultrasound
   root_dir: '/media/WDportable/MotionModelling_PMB/114CTarchive_vol04'
   input_dir: 'pairs/US'
   output_dir: 'pairs/CT'
   data_dir: ''
   navi_dir: ''
   us_dir: ''
   n_slices: 0
   n_sweeps: 0
   n_training_sweeps: 0
   master_navi: ''
   master_volume: 'pairs/CT/train/deformationfield_0000.mha'
   input_format: 'png'
   output_format: 'mha'

# 2D Registration (for navis only)
reg2d:
  - ''

# 3D Registration
reg3d:
   - ''

# Gaussian Processes Regression (GPR)
# If you run GPR for test set, the features are overwritten and have to be recomputed for the training set afterwards.
# In that case, set 'use_precomputed_features' to 1
gpr:
   subdir: 'test'
   kernel_string: '"GaussianKernel(35, 30,)"'
   data_noise: '1.0'
   n_inputModes: '176'
   n_outputModes: '8'
   use_precomputed: 1
   use_precomputed_features: 0
